[theme]
base = "light"
primaryColor = "#f0a202"
backgroundColor = "#e9eef5"
secondaryBackgroundColor = "#d7e0eb"
textColor = "#0b1d36"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false
